### PR TITLE
Move utils.py to _common/ as _constructs.py

### PR DESCRIPTION
**Pull request by ashfall**

### CODE REVIEW

**Comment by ashfall** [comment]
This might cause some conflicts once #91 is merged, so we might want to close #91 first. Nevertheless, this branch is ready for review.

**Comment by markrwilliams** [comment]
@ashfall - this looks good overall.  One thing: `tls._common.test.test_constructs` has docstrings with references to `tls.utils` like [this one](https://github.com/ashfall/tls/blob/1806178745bfd4f041fca452f4c5fecf33cfac8c/tls/_common/test/test_constructs.py#L42).  

Once those get fixed I'll merge this!

**Comment by ashfall** [comment]
Good catch, thanks! Updated.

**Comment by markrwilliams** [comment]
@ashfall You move quickly! Good catch with the spelling correction.  I'll merge once the next build

**Comment by ashfall** [comment]
@markrwilliams  Thanks! I *think* there shouldn't be any conflicts for #91, but I'll fix if any show up.

**Comment by markrwilliams** [comment]
@ashfall I'm going to merge #91 first!

**Comment by markrwilliams** [comment]
@ashfall nuts it has conflicts :(

**Comment by ashfall** [comment]
I am not surprised :). Fixing, give me a few minutes.

**Comment by markrwilliams** [comment]
@ashfall Thanks!!

**Pull request merged**
