### PR TITLE
Use attrs instead of characteristic

### LINKED ISSUE #83: Use `attrs` instead of `characteristic`.
Quoting from the [`characteristic` README](https://github.com/hynek/characteristic/blob/master/README.rst):

> Please note that characteristic is in a bugfix-only mode. For new features please have a look at its successor attrs.

So, we should work on switching to [`attrs`](https://attrs.readthedocs.io/en/stable/).

### PR DESCRIPTION
**Pull request by ashfall**
`characteristic` is in a bugfix-only mode, this change moves us away from it and uses the more actively maintained library, `attrs`. Fixes #83.

### CODE REVIEW

**Comment by markrwilliams** [comment]
Looks great!  I think the new `attrs` style reads nicely.
Please (rebase and) merge so we can start using it :)

**Comment by ashfall** [comment]
Thanks for the review!
From https://github.com/pyca/tls/blob/master/CONTRIBUTING.rst#merge-requirements:
`A committer may _never_ merge their own pull request, a second party must merge their changes.`

Can someone please merge this PR once they find it satisfactory? 
Relatedly, @markrwilliams would you like commit rights so you can merge other PRs?

**Comment by markrwilliams** [comment]
@ashfall Sure!! If I get commit rights before this patch is merged, it'll be OK for me to merge it, yes?

**Comment by ashfall** [comment]
@markrwilliams That was the idea, yes :)

**Comment by markrwilliams** [comment]
@ashfall it looks like you prefer to use Github's "Merge pull request" button with the "Squash and merge" option.  Shall I do the same?

**Comment by ashfall** [comment]
@markrwilliams Go for it!  Thank you!! :)

**Pull request merged**
